### ISSUE TITLE
ABI Issue

### ISSUE THREAD

**Issue by CamArmstr** [stevenpslade/maas#1]
I forked and pulled down, but the forked branch was missing the Multisig ABI and the lack of ABI import made the front app not compile right. Once I created an ABI from the compiled contract and put it in the right folder it rendered properly! 

![image](https://user-images.githubusercontent.com/52431864/163629055-52e9abad-d76a-4ac1-9f5f-8f076f6507ff.png)
@stevenpslade

**Comment by CamArmstr** [comment]
I can PR this if you want so the master works out of the box!

**Comment by stevenpslade** [comment]
Thanks for this! Looks like this has been taken care of in https://github.com/austintgriffith/maas which I have since synced this repo up with.
